### ISSUE TITLE
Getting an error that `'GIT_DESCRIBE' is not defined`

### ISSUE THREAD

**Issue by Jont828** [idelsink/vue-cli-plugin-git-describe#34]
Hi, I ran `vue add git-describe` in my project, which added the following lines to my vue.config.js file.

```
  ...
  pluginOptions: {
    gitDescribe: {
      variableName: 'GIT_DESCRIBE'
    }
  }
}
```

I attempted to access the `GIT_DESCRIBE` variable in one of my views in the `mounted()` section as follows

```
mounted() {
  console.log("App version", GIT_DESCRIBE.raw);
},
```

and got an error saying that `'GIT_DESCRIBE' is not defined`. Am I missing something here?

**Comment by idelsink** [comment]
Hey @Jont828, can you share the complete error message?

Is it by any chance related to eslint? If I follow the example steps in this plugin, I see that I get an eslint config error. Perhaps some defaults have changed and now undefined globals are treated as errors.

```
$ vue-cli-service serve --mode development --dashboard
 INFO  Starting development server...

[3%] setup (watch run)
[9%] setup (compilation WebpackIsIncludedPlugin)
[24%] building (import loader css-loader/dist/cjs.js)
[65%] building (123/123 modules)
[85%] sealing (chunk id optimization)
 ERROR  Failed to compile with 1 error11:25:11 PM

[eslint] 
/home/ingmar/Workspace/vue-test-app/test-app/src/main.js
  6:28  error  'GIT_DESCRIBE' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

ERROR in [eslint] 
/home/ingmar/Workspace/vue-test-app/test-app/src/main.js
  6:28  error  'GIT_DESCRIBE' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)


webpack compiled with 1 error
```

If the above mentioned error is your problem you can solve it by:

1. Adding `// eslint-disable-next-line` or `/* global GIT_DESCRIBE:readonly */`above the statement where you use `GIT_DESCRIBE`. E.g.:

```js
/* global GIT_DESCRIBE:readonly */
console.log('App version', GIT_DESCRIBE.raw);
```
 2. Or you can set it in the eslint (package.json or .eslint.*) config as:
```json
"globals": {
  "GIT_DESCRIBE": "readonly"
},
```

What I probably need to do is to update the readme to include this info, and potentially add a prompt so that this can be done automatically when installing the plugin.

**Comment by Jont828** [comment]
Sorry for the late response, but yes, both of those options seemed to work for me!
